# Generated by Django 5.0.7 on 2024-08-06 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_productinfo_name_productinfo_model_shop_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='backend.contact', verbose_name='Владелец'),
        ),
    ]
